---
- name: set openshift dns servers variable
  set_fact:
    openshift_dns_servers: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  with_items: "{{ groups.dns }}"

- name: install NetworkManager
  package:
    name: NetworkManager
    state: present

- name: configure NetworkManager
  template:
    src: nm.conf.j2
    dest: /etc/NetworkManager/conf.d/nm.conf
    owner: root
    group: root
    mode: 0644
  notify: restart NetworkManager
