---
- name: fetch bastion host id_rsa.pub file content 
  shell: "cat {{ openshift_bastion_user_home }}/.ssh/id_rsa.pub"
  register: ssh_keys
  when: inventory_hostname in groups['bastions']

- name: set ssh key variable on bastion host
  set_fact:
    bastion_ssh_key: "{{ ssh_keys.stdout }}"
  when: inventory_hostname in groups['bastions']

- name: set ssh key variable on other hosts
  set_fact:
    bastion_ssh_key: "{{ hostvars['bastion-test']['bastion_ssh_key'] }}"
  when: inventory_hostname not in groups['bastions']

- name: disable host key checking
  lineinfile:
    dest: /etc/ssh/ssh_config
    line: "StrictHostKeyChecking no"
  when: inventory_hostname in groups['bastions']

- name: make sure bastion ssh key is in hosts authorized_keys
  authorized_key:
    state: present
    user: root
    key: "{{ bastion_ssh_key }}"
  when: inventory_hostname not in groups['bastions']
