---
- import_tasks: configure_dns.yml
  when: inventory_hostname in groups['bastions']

- name: flush handlers
  meta: flush_handlers
  when: inventory_hostname in groups['bastions']

- import_tasks: configure_ansible.yml
  when: inventory_hostname in groups['bastions']

- import_tasks: configure_authorized_keys.yml
