---
- name: set openshift dns servers variable
  set_fact:
    openshift_dns_servers: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  with_items: "{{ groups.dns }}"

- name: set temporarily DNS server to resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root

- import_tasks: configure_dns.yml
  when: inventory_hostname in groups['bastions']

- name: flush handlers
  meta: flush_handlers
  when: inventory_hostname in groups['bastions']

- import_tasks: configure_ansible.yml
  when: inventory_hostname in groups['bastions']

- import_tasks: configure_authorized_keys.yml
